name: Update profile trophies

on:
  schedule:
    - cron: "45 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  trophies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ryo-ma/github-profile-trophy@master
        with:
          username: ${{ github.repository_owner }}
          output_path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: dracula
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull origin main --rebase || true
          git add trophy.svg
          git commit -m "Update profile trophies" || exit 0
          git push
